version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: product-service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwordadmin
      POSTGRES_DB: productservice_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local
